# -*- coding: utf-8 -*-
"""CNN-FASHION.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1275Gd-Vpl1RkbM2DZzNC1BFkjAFSYQTT
"""

import tensorflow as tf
from tensorflow import keras
mnistDB=keras.datasets.fashion_mnist
(x_train,y_train),(x_test,y_test)=mnistDB.load_data()
print("shape of x_train",x_train.shape)
print("shape of x_test",x_test.shape)
print("shape of y_train",y_train.shape)
print("shape of y_test",y_test.shape)

import matplotlib.pyplot as plt
plt.imshow(x_train[2],cmap='binary')

x_train=x_train.reshape((60000,28,28,1))
x_test=x_test.reshape((10000,28,28,1))
x_train=x_train.astype('float32')/255
x_test=x_test.astype('float32')/255
cnnmodel_mnist=keras.models.Sequential()
cnnmodel_mnist.add(keras.layers.Conv2D(32,(3,3),activation='relu',input_shape=x_train.shape[1:]))
cnnmodel_mnist.add(keras.layers.Conv2D(64,(3,3),activation='relu'))
cnnmodel_mnist.add(keras.layers.MaxPooling2D(2,2))
cnnmodel_mnist.add(keras.layers.Flatten())
cnnmodel_mnist.add(keras.layers.Dense(128,activation='relu'))
cnnmodel_mnist.add(keras.layers.Dropout(0.25))
cnnmodel_mnist.add(keras.layers.Dense(10,activation='softmax'))
cnnmodel_mnist.summary()
cnnmodel_mnist.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
cnnmodel_mnist.fit(x_train,y_train,epochs=1,batch_size=16)
test_loss,test_accuracy=cnnmodel_mnist.evaluate(x_test,y_test)
print(test_loss,test_accuracy)